export const SORT_PRICE = 'SORT_PRICE';
export const SORT_SPEED = 'SORT_SPEED';
export const SORT_OPTIMAL = 'SORT_OPTIMAL';
export const TRANSFERS_FILTER_PROPERTY_TOGGLE = 'TRANSFERS_FILTER_PROPERTY_TOGGLE';
export const FIRST_TICKETS_PACK_LOADED = 'FIRST_TICKETS_PACK_LOADED';
export const ALL_TICKETS_LOADED = 'ALL_TICKETS_LOADED';
