export const SORT_PRICE = 'SORT_PRICE';
export const SORT_SPEED = 'SORT_SPEED';
export const TRANSFERS_FILTER_ALL_STOPS_TOGGLE = 'TRANSFERS_FILTER_ALL_STOPS_TOGGLE';
export const TRANSFERS_FILTER_NON_STOPS_TOGGLE = 'TRANSFERS_FILTER_NON_STOPS_TOGGLE';
export const TRANSFERS_FILTER_ONE_STOPS_TOGGLE = 'TRANSFERS_FILTER_ONE_STOPS_TOGGLE';
export const TRANSFERS_FILTER_TWO_STOPS_TOGGLE = 'TRANSFERS_FILTER_TWO_STOPS_TOGGLE';
export const TRANSFERS_FILTER_THREE_STOPS_TOGGLE = 'TRANSFERS_FILTER_THREE_STOPS_TOGGLE';
export const TICKETS_LOADED = 'TICKETS_LOADED';
